### ISSUE TITLE
General Use Difficulty

### ISSUE THREAD

**Issue by ghost** [mseok/PIGNet2#2]
Hello, 
I'm trying to use PIGNet2 as a re-scoring tool, and I came upon a wall of needing to dig through the code trying to figure out how can I apply this tool to data that is not the supplied benchmarks. Is there a more generic usage protocol or manual? 

What I'm trying to do specifically is to use PIGNet2 as a re-scoring tool for the results from Autodock Vina virtual screening, and currently I can't seem to find any manual on how I can prepare my data for scoring with the pretrained model.

**Comment by mseok** [comment]
Sorry for late response.
Now you can check the `src/exe/predict.py` and usecases in `README.md`
