### ISSUE TITLE
Output format

### ISSUE THREAD

**Issue by sistar2020** [mseok/PIGNet2#3]
Can you explain the columns in output files?
For example, the content of examples/case1.txt is as below.
Because this file does not have a header, it's hard to figure out what these columns represent.

```
$ cat examples/case1.txt
protein_ligand_single_conformation_0    0.000   -3.990  -2.074  -1.021  0.000   -0.894  0.000
```

My best guess is -3.990 is the total energy which corresponds to the sum of energy components (-2.074,  -1.021,  0.000,   -0.894 and 0.000).
It will be appreciated if some comments are added on the output.

**Comment by sangyeon-hits** [comment]
Hello sistar2020,

Each of the numeric columns corresponds to:

1. True label (which is just set to 0.000 in inference)
2. Total predicted binding affinity (= sum of the right-hand values)
3. van der Waals energy
4. hydrogen bond energy
5. metal-ligand coordination energy
6. hydrophobic energy
7. dummy variable (please ignore this column)
