### ISSUE TITLE
generate_data.py, generate_conformer.py 처리시 "Unkekulized atoms" Error 문의 

### ISSUE THREAD

**Issue by seohyeonShin** [mseok/PIGNet2#6]
안녕하세요, 
데이터 전처리를 직접 해보고 싶어서 직접 돌려보고 있습니다. 

"refined-set"에서 다운받은 데이터중에 690여개 데이터에서 같은 이슈가 발생하는데요. 
예를들어 "5u13" 라면 아래와 같이 에러가 발생합니다. 

미리 처리하여 올려주신 download.sh로 받은 데이터를 보면 처리 하신후 증강까지 하셨는데.. 
혹시 어떤 다른 처리를 하셨을까요? 어떤 과정으로 해야할지 조언을 부탁드립니다. 

(pignet2) (base) jovyan@ch:~/store1/IRC_workspace$ python /home/jovyan/store1/IRC_workspace/Origin/PIGNet2/dataset/generate_PDA/generate_conformers.py /home/jovyan/store1/jenny_DATA/IRC/refined-set 5u13 --uff --mmff
[09:43:36] Can't kekulize mol.  Unkekulized atoms: 2 9 10 13 15 16
Traceback (most recent call last):
  File "/home/jovyan/store1/IRC_workspace/Origin/PIGNet2/dataset/generate_PDA/generate_conformers.py", line 98, in <module>
    main()
  File "/home/jovyan/store1/IRC_workspace/Origin/PIGNet2/dataset/generate_PDA/generate_conformers.py", line 69, in main
    ligand, confids = generate_conformers(ligand, ps)
  File "/home/jovyan/store1/IRC_workspace/Origin/PIGNet2/dataset/generate_PDA/generate_conformers.py", line 32, in generate_conformers
    confids = AllChem.EmbedMultipleConfs(mol, n_confs, ps)
rdkit.Chem.rdchem.KekulizeException: Can't kekulize mol.  Unkekulized atoms: 2 9 10 13 15 16

**Comment by sangyeon-hits** [comment]
안녕하세요,

저희가 [Zenodo](https://zenodo.org/records/8091220)에 올린 전처리가 된 데이터가 아니라, 원본 PDBbind 데이터 파일로부터 작업을 해보시려는 걸로 이해했습니다.

## 문제

PDBbind에서 제공하는 리간드 데이터 파일은 화학결합 차수나 원자의 전하 등에 오류가 많이 있습니다.
해당 파일들은 쉽게 표현하자면 RDKit이나 Open Babel 같은 도구로 읽을 때 오류가 납니다.

예를 들어 말씀하신 [5U13](https://www.rcsb.org/structure/5U13)의 리간드의 경우 올바른 리간드 구조와 PDBbind에 의한 구조들이 아래처럼 다릅니다:
![5u13](https://github.com/user-attachments/assets/75a1a32b-b664-4989-a167-250ec4804255)

위 예처럼 주로 heteroaromatic ring에서 오류가 많으며, 그런 경우 특히 Kekulize 오류가 나기 쉽습니다.

## 해결

저희는 직접 다음처럼 리간드 파일들을 수정하여 사용하였습니다.

1. RCSB 및 해당 PDB를 보고한 논문에서 리간드의 가장 올바른 2D 구조 추출 (즉, 올바른 SMILES 목록 정리).
2. PDBbind의 `.sdf` 파일들에 1에서 구한 SMILES를 적용 (RDKit의 [`AssignBondOrdersFromTemplate`](https://www.rdkit.org/docs/source/rdkit.Chem.AllChem.html#rdkit.Chem.AllChem.AssignBondOrdersFromTemplate) 사용).
3. 2에서 실패하는 드문 경우, PyMOL과 같은 분자 구조 편집기를 이용해 직접 결합 차수 수정.

저희가 Zenodo에 공유한 파일들은 위처럼 직접 교정한 후 [`rdkit.Chem.Mol`](https://www.rdkit.org/docs/source/rdkit.Chem.rdchem.html#rdkit.Chem.rdchem.Mol) object로 변환하여 pickling 한 파일들입니다.

위 1-3처럼 직접 작업을 하셔도 되고, 혹은 저희가 공유한 데이터를 이용해 아래처럼 `.sdf` 파일을 만들어 사용하셔도 됩니다.

```python
import pickle

from rdkit.Chem import AllChem as Chem

with open("5u13", "rb") as f:
    mols: tuple[Chem.Mol, Chem.Mol] = pickle.load(f)
    ligand_mol, pocket_mol = mols

with Chem.SDWriter("5u13_ligand.sdf") as writer:
    # Note that `ligand_mol` had been saved with explicit Hs.
    writer.write(ligand_mol)
```

## 첨언

[PDBbind v2021](https://www.pdbbind-plus.org.cn)에서는 데이터 파일들을 더 정제했다고 하는데, 저희는 사용해보지 않아서 위 같은 오류들도 고쳐졌는지는 모르겠습니다.
